// examples/front-end/vue/apollo-composable/src/App.vue
<script setup lang="ts">
import { useQuery } from '@vue/apollo-composable';
import { gql } from './gql/gql';
import FilmItem from './components/FilmItem.vue';
import { computed } from 'vue';

const { result } = useQuery(
  gql(/* GraphQL */ `
    query allFilmsWithVariablesQuery($first: Int!) {
      allFilms(first: $first) {
        edges {
          node {
            ...FilmItem
          }
        }
      }
    }
  `),
  { first: 10 }
);
const films = computed(() => result.value?.allFilms?.edges?.map(e => e?.node!));
</script>

<template>
  <ul>
    <li v-for="film of films"><FilmItem :film="film" /></li>
  </ul>
</template>

// examples/front-end/react/apollo-client/src/App.tsx
import React from 'react';
import { useQuery } from '@apollo/client';
import './App.css';
import Film from './Film';
import { gql } from './gql/gql';

const allFilmsWithVariablesQueryDocument = gql(/* GraphQL */ `
  query allFilmsWithVariablesQuery($first: Int!) {
    allFilms(first: $first) {
      edges {
        node {
          ...FilmItem
        }
      }
    }
  }
`);

function App() {
  const { data } = useQuery(allFilmsWithVariablesQueryDocument, { variables: { first: 10 } });
  return (
    <div className="App">
      {data && <ul>{data.allFilms?.edges?.map((e, i) => e?.node && <Film film={e?.node} key={`film-${i}`} />)}</ul>}
    </div>
  );
}

export default App;
